# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_logo',
        ),
    ]
