# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
