# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20171126_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='follower',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
