# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171126_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
    ]
