# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following', to='channels.Channel'),
        ),
    ]
