# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20171122_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
