# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20171122_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_logo',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='nsfw',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
    ]
