# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20171122_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
